### ISSUE TITLE
Feature request - use ESC key to clear tape content

### ISSUE THREAD

**Issue by jobytoss** [4silvertooth/QwikTape#5] opened 2023-04-08 10:45 UTC
Hello!
I started using QwikTape since it became portable (also added it to the TPFC database https://www.portablefreeware.com/?id=3090 ) and wish I could use ESC key to clear the tape (delete all contents, calculus and annotations) and double ESC key to close the app. This would greatly increase my workflow speed. 
Thank you!

**Comment by 4silvertooth** [comment] 2023-04-08 15:26
@jobytoss 
Wouldn't a double escape to exit be risky if there is a single escape to clear the content, sometimes it might not work as intended, and user might loose the tape? 
I will definitely add keyboard shortcuts for closing tab, adding new tab.

*Edit
Also uploading portable version for windows, linux and macos.

**Comment by jobytoss** [comment] 2023-04-08 19:18
I hoped that ESC key could somehow work as "Clear tape contents" when the active tape has something written in it and as "Alt+F4" if active tape is empty. 
Thank you for the answer!

**Closed as completed** 2023-04-11 12:04 UTC
